# -*- coding: utf-8 -*-

SCORM_12_RUNTIME_DEFAULT = {'cmi.comments': '',
 'cmi.comments_from_lms': '',
 'cmi.core._children': ['student_id',
  'student_name',
  'lesson_location',
  'credit',
  'lesson_status',
  'entry',
  'score',
  'total_time',
  'lesson_mode',
  'exit',
  'session_time'],
 'cmi.core.credit': 'credit',
 'cmi.core.entry': '',
 'cmi.core.exit': '',
 'cmi.core.lesson_location': '',
 'cmi.core.lesson_mode': 'normal',
 'cmi.core.lesson_status': 'not attempted',
 'cmi.core.score.max': 0.0,
 'cmi.core.score.min': 0.0,
 'cmi.core.score.raw': 0.0,
 'cmi.core.score_children': ['raw', 'min', 'max'],
 'cmi.core.session_time': 0,
 'cmi.core.student_id': '',
 'cmi.core.student_name': '',
 'cmi.core.total_time': '0000:00:00.00',
 'cmi.interactions._children': ['id',
  'objectives',
  'time',
  'type',
  'correct_responses',
  'weighting',
  'student_response',
  'result',
  'latency'],
 'cmi.interactions._count': 0,
 'cmi.interactions.n.correct_responses._count': 0,
 'cmi.interactions.n.correct_responses.n.pattern': '',
 'cmi.interactions.n.id': '',
 'cmi.interactions.n.latency': 0,
 'cmi.interactions.n.objectives._count': 0,
 'cmi.interactions.n.objectives.n.id': '',
 'cmi.interactions.n.result': 'unanticipated',
 'cmi.interactions.n.student_response': '',
 'cmi.interactions.n.time': 0,
 'cmi.interactions.n.type': 'numeric',
 'cmi.interactions.n.weighting': 0.0,
 'cmi.launch_data': '',
 'cmi.objectives._children': ['id', 'score', 'status'],
 'cmi.objectives._count': 0,
 'cmi.objectives.n.id': '',
 'cmi.objectives.n.score._children': ['raw', 'min', 'max'],
 'cmi.objectives.n.score.max': 0.0,
 'cmi.objectives.n.score.min': 0.0,
 'cmi.objectives.n.score.raw': 0.0,
 'cmi.objectives.n.status': 'not attempted',
 'cmi.student_data._children': ['mastery_score',
  'max_time_allowed',
  'time_limit_action'],
 'cmi.student_data.mastery_score': 0.0,
 'cmi.student_data.max_time_allowed': '',
 'cmi.student_data.time_limit_action': 'continue, no message',
 'cmi.student_preference._children': ['audio', 'language', 'speed', 'text'],
 'cmi.student_preference.audio': '',
 'cmi.student_preference.language': '',
 'cmi.student_preference.speed': '',
 'cmi.student_preference.text': '',
 'cmi.suspend_data': ''}




SCORM_2004_RUNTIME_DEFAULT = {'cmi._version': '',
 'cmi.comments_from_learner._children': ['comment', 'location', 'timestamp'],
 'cmi.comments_from_learner._count': 0,
 'cmi.comments_from_learner.n.comment': '',
 'cmi.comments_from_learner.n.location': 0,
 'cmi.comments_from_learner.n.timestamp': 0,
 'cmi.comments_from_lms._children': ['comment', 'location', 'timestamp'],
 'cmi.comments_from_lms._count': 0,
 'cmi.comments_from_lms.n.comment': '',
 'cmi.comments_from_lms.n.location': 0,
 'cmi.comments_from_lms.n.timestamp': 0,
 'cmi.completion_status': 'unknown',
 'cmi.completion_threshold': 0.0,
 'cmi.credit': 'credit',
 'cmi.entry': '',
 'cmi.exit': '',
 'cmi.interactions._children': ['id',
  'type',
  'objectives',
  'timestamp',
  'correct_responses',
  'weighting',
  'learner_response',
  'result',
  'latency',
  'description'],
 'cmi.interactions._count': 0,
 'cmi.interactions.n.correct_responses._count': 0,
 'cmi.interactions.n.correct_responses.n.pattern': '',
 'cmi.interactions.n.description': '',
 'cmi.interactions.n.id': 0,
 'cmi.interactions.n.latency': 0,
 'cmi.interactions.n.learner_response': '',
 'cmi.interactions.n.objectives._count': 0,
 'cmi.interactions.n.objectives.n.id': 0,
 'cmi.interactions.n.result': 'unanticipated',
 'cmi.interactions.n.timestamp': 0,
 'cmi.interactions.n.type': 'other',
 'cmi.interactions.n.weighting': 0.0,
 'cmi.launch_data': '',
 'cmi.learner_id': 0,
 'cmi.learner_name': '',
 'cmi.learner_preference._children': ['audio_level',
  'language',
  'delivery_speed',
  'audio_captioning'],
 'cmi.learner_preference.audio_captioning': '0',
 'cmi.learner_preference.audio_level': 0.0,
 'cmi.learner_preference.delivery_speed': 0.0,
 'cmi.learner_preference.language': '',
 'cmi.location': '',
 'cmi.max_time_allowed': '',
 'cmi.mode': 'normal',
 'cmi.objectives._children': ['id',
  'score',
  'success_status',
  'completion_status',
  'description'],
 'cmi.objectives._count': 0,
 'cmi.objectives.n.completion_status': 'unknown',
 'cmi.objectives.n.description': '',
 'cmi.objectives.n.id': 0,
 'cmi.objectives.n.progress_measure': 0.0,
 'cmi.objectives.n.score._children': ['scaled', 'raw', 'min', 'max'],
 'cmi.objectives.n.score.max': 0.0,
 'cmi.objectives.n.score.min': 0.0,
 'cmi.objectives.n.score.raw': 0.0,
 'cmi.objectives.n.score.scaled': 0.0,
 'cmi.objectives.n.success_status': 'unknown',
 'cmi.progress_measure': 0.0,
 'cmi.scaled_passing_score': 0.0,
 'cmi.score._children': ['scaled', 'raw', 'min', 'max'],
 'cmi.score.max': 0.0,
 'cmi.score.min': 0.0,
 'cmi.score.raw': 0.0,
 'cmi.score.scaled': 0.0,
 'cmi.session_time': 0,
 'cmi.success_status': 'unknown',
 'cmi.suspend_data': '',
 'cmi.time_limit_action': 'continue,no message',
 'cmi.total_time': 'PT0S'}

